/**
 * Gate API v4
 * Welcome to Gate API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user\'s behalf.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Quotation Response
 */
export class AccountBookResponse {
    /**
     * Order ID
     */
    'id'?: number;
    /**
     * 操作时间戳
     */
    'time'?: number;
    /**
     * Currency name
     */
    'currency'?: string;
    /**
     * Change amount
     */
    'change'?: string;
    /**
     * 变更后余额
     */
    'balance'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'id',
            baseName: 'id',
            type: 'number',
        },
        {
            name: 'time',
            baseName: 'time',
            type: 'number',
        },
        {
            name: 'currency',
            baseName: 'currency',
            type: 'string',
        },
        {
            name: 'change',
            baseName: 'change',
            type: 'string',
        },
        {
            name: 'balance',
            baseName: 'balance',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return AccountBookResponse.attributeTypeMap;
    }
}
