/**
 * Gate API
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Total balances calculated with specified currency unit
 */
export class AccountBalance {
    /**
     * Account total balance amount
     */
    'amount'?: string;
    /**
     * Currency
     */
    'currency'?: AccountBalance.Currency;
    /**
     * Unrealised_pnl, this field will only appear in futures, options, delivery, and total accounts
     */
    'unrealisedPnl'?: string;
    /**
     * Borrowed，this field will only appear in margin and cross_margin accounts
     */
    'borrowed'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'amount',
            baseName: 'amount',
            type: 'string',
        },
        {
            name: 'currency',
            baseName: 'currency',
            type: 'AccountBalance.Currency',
        },
        {
            name: 'unrealisedPnl',
            baseName: 'unrealised_pnl',
            type: 'string',
        },
        {
            name: 'borrowed',
            baseName: 'borrowed',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return AccountBalance.attributeTypeMap;
    }
}

export namespace AccountBalance {
    export enum Currency {
        BTC = <any>'BTC',
        CNY = <any>'CNY',
        USD = <any>'USD',
        USDT = <any>'USDT',
    }
}
