/**
 * Gate API v4
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user\'s behalf.
 *
 * Contact: support@mail.gate.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class ApiV4KeyPerm {
    /**
     * Permission name (all permissions will be removed if no value is passed)  - wallet: wallet - spot: spot/margin - futures: perpetual contract - delivery: delivery - earn: earn - options: options- account: Account - portfolio: Portfolio - loan: Loan
     */
    'name'?: ApiV4KeyPerm.Name;
    /**
     * read only
     */
    'readOnly'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'name',
            baseName: 'name',
            type: 'ApiV4KeyPerm.Name',
        },
        {
            name: 'readOnly',
            baseName: 'read_only',
            type: 'boolean',
        },
    ];

    static getAttributeTypeMap() {
        return ApiV4KeyPerm.attributeTypeMap;
    }
}

export namespace ApiV4KeyPerm {
    export enum Name {
        Wallet = <any>'wallet',
        Spot = <any>'spot',
        Futures = <any>'futures',
        Delivery = <any>'delivery',
        Earn = <any>'earn',
        Options = <any>'options',
        Account = <any>'account',
        Portfolio = <any>'portfolio',
        Loan = <any>'loan',
    }
}
