/**
 * Gate API
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class AutoRepaySetting {
    /**
     * Auto repayment status. `on` - enabled, `off` - disabled.
     */
    'status'?: AutoRepaySetting.Status;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'status',
            baseName: 'status',
            type: 'AutoRepaySetting.Status',
        },
    ];

    static getAttributeTypeMap() {
        return AutoRepaySetting.attributeTypeMap;
    }
}

export namespace AutoRepaySetting {
    export enum Status {
        On = <any>'on',
        Off = <any>'off',
    }
}
