/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Sub-broker information
 */
export class BrokerCommissionSubBrokerInfo {
    /**
     * Sub-broker user ID
     */
    'userId'?: number;
    /**
     * Sub-broker original commission rate
     */
    'originalCommissionRate'?: string;
    /**
     * Sub-broker relative commission rate
     */
    'relativeCommissionRate'?: string;
    /**
     * Sub-broker actual commission rate
     */
    'commissionRate'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'userId',
            baseName: 'user_id',
            type: 'number',
        },
        {
            name: 'originalCommissionRate',
            baseName: 'original_commission_rate',
            type: 'string',
        },
        {
            name: 'relativeCommissionRate',
            baseName: 'relative_commission_rate',
            type: 'string',
        },
        {
            name: 'commissionRate',
            baseName: 'commission_rate',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return BrokerCommissionSubBrokerInfo.attributeTypeMap;
    }
}
