/**
 * Gate API v4
 * Welcome to Gate API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user\'s behalf.
 *
 * Contact: support@mail.gate.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class CollateralAlign {
    /**
     * Order ID
     */
    'orderId': number;
    /**
     * Collateral
     */
    'collateralCurrency': string;
    /**
     * Collateral amount
     */
    'collateralAmount': string;
    /**
     * Operation types: append - for adding collateral, redeem - for withdrawing collateral
     */
    'type': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'orderId',
            baseName: 'order_id',
            type: 'number',
        },
        {
            name: 'collateralCurrency',
            baseName: 'collateral_currency',
            type: 'string',
        },
        {
            name: 'collateralAmount',
            baseName: 'collateral_amount',
            type: 'string',
        },
        {
            name: 'type',
            baseName: 'type',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return CollateralAlign.attributeTypeMap;
    }
}
