/**
 * Gate API v4
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user\'s behalf.
 *
 * Contact: support@mail.gate.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Collateral Ratio
*/
export class CollateralLtv {
    /**
    * The initial collateralization rate
    */
    'initLtv'?: string;
    /**
    * Warning collateralization ratio
    */
    'alertLtv'?: string;
    /**
    * The liquidation collateralization rate
    */
    'liquidateLtv'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "initLtv",
            "baseName": "init_ltv",
            "type": "string"
        },
        {
            "name": "alertLtv",
            "baseName": "alert_ltv",
            "type": "string"
        },
        {
            "name": "liquidateLtv",
            "baseName": "liquidate_ltv",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CollateralLtv.attributeTypeMap;
    }
}

