/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Collateral record
 */
export class CollateralRecord {
    /**
     * Order ID
     */
    'orderId'?: number;
    /**
     * Collateral record ID
     */
    'recordId'?: number;
    /**
     * Borrowed currency
     */
    'borrowCurrency'?: string;
    /**
     * Borrowed amount
     */
    'borrowAmount'?: string;
    /**
     * Collateral currency
     */
    'collateralCurrency'?: string;
    /**
     * Collateral amount before adjustment
     */
    'beforeCollateral'?: string;
    /**
     * Collateral amount after adjustment
     */
    'afterCollateral'?: string;
    /**
     * Collateral ratio before adjustment
     */
    'beforeLtv'?: string;
    /**
     * Collateral ratio after adjustment
     */
    'afterLtv'?: string;
    /**
     * Operation time, timestamp in seconds
     */
    'operateTime'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'orderId',
            baseName: 'order_id',
            type: 'number',
        },
        {
            name: 'recordId',
            baseName: 'record_id',
            type: 'number',
        },
        {
            name: 'borrowCurrency',
            baseName: 'borrow_currency',
            type: 'string',
        },
        {
            name: 'borrowAmount',
            baseName: 'borrow_amount',
            type: 'string',
        },
        {
            name: 'collateralCurrency',
            baseName: 'collateral_currency',
            type: 'string',
        },
        {
            name: 'beforeCollateral',
            baseName: 'before_collateral',
            type: 'string',
        },
        {
            name: 'afterCollateral',
            baseName: 'after_collateral',
            type: 'string',
        },
        {
            name: 'beforeLtv',
            baseName: 'before_ltv',
            type: 'string',
        },
        {
            name: 'afterLtv',
            baseName: 'after_ltv',
            type: 'string',
        },
        {
            name: 'operateTime',
            baseName: 'operate_time',
            type: 'number',
        },
    ];

    static getAttributeTypeMap() {
        return CollateralRecord.attributeTypeMap;
    }
}
