/**
 * Gate API v4
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user\'s behalf.
 *
 * Contact: support@mail.gate.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Countdown cancel task detail
 */
export class CountdownCancelAllSpotTask {
    /**
     * Countdown time, in seconds  At least 5 seconds, 0 means cancel the countdown
     */
    'timeout': number;
    /**
     * Currency pair
     */
    'currencyPair'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'timeout',
            baseName: 'timeout',
            type: 'number',
        },
        {
            name: 'currencyPair',
            baseName: 'currency_pair',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return CountdownCancelAllSpotTask.attributeTypeMap;
    }
}
