/**
 * Gate API
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Countdown cancel task detail
 */
export class CountdownCancelAllFuturesTask {
    /**
     * Countdown time in seconds At least 5 seconds, 0 means cancel countdown
     */
    'timeout': number;
    /**
     * Futures contract
     */
    'contract'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'timeout',
            baseName: 'timeout',
            type: 'number',
        },
        {
            name: 'contract',
            baseName: 'contract',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return CountdownCancelAllFuturesTask.attributeTypeMap;
    }
}
