/**
 * Gate API v4
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user\'s behalf.
 *
 * Contact: support@mail.gate.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Lend or redeem
*/
export class CreateUniLend {
    /**
    * Currency name
    */
    'currency': string;
    /**
    * The amount of currency could be lent
    */
    'amount': string;
    /**
    * type: lend - lend, redeem - redeem
    */
    'type': CreateUniLend.Type;
    /**
    * The minimum interest rate. If the value is too high, it might lead to the unsuccessful lending and no profit will be gained for that hour. 
    */
    'minRate'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "CreateUniLend.Type"
        },
        {
            "name": "minRate",
            "baseName": "min_rate",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateUniLend.attributeTypeMap;
    }
}

export namespace CreateUniLend {
    export enum Type {
        Lend = <any> 'lend',
        Redeem = <any> 'redeem'
    }
}
