/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Create lending or redemption
 */
export class CreateUniLend {
    /**
     * Currency name
     */
    'currency': string;
    /**
     * Amount to deposit into lending pool
     */
    'amount': string;
    /**
     * Operation type: lend - Lend, redeem - Redeem
     */
    'type': CreateUniLend.Type;
    /**
     * Minimum interest rate. If set too high, lending may fail and no interest will be earned. Required for lending operations.
     */
    'minRate'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'currency',
            baseName: 'currency',
            type: 'string',
        },
        {
            name: 'amount',
            baseName: 'amount',
            type: 'string',
        },
        {
            name: 'type',
            baseName: 'type',
            type: 'CreateUniLend.Type',
        },
        {
            name: 'minRate',
            baseName: 'min_rate',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return CreateUniLend.attributeTypeMap;
    }
}

export namespace CreateUniLend {
    export enum Type {
        Lend = <any>'lend',
        Redeem = <any>'redeem',
    }
}
