/**
 * Gate API v4
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user\'s behalf.
 *
 * Contact: support@mail.gate.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class CrossMarginAccountBook {
    /**
     * Balance change record ID
     */
    'id'?: string;
    /**
     * The timestamp of the change (in milliseconds)
     */
    'time'?: number;
    /**
     * Currency changed
     */
    'currency'?: string;
    /**
     * Amount changed. Positive value means transferring in, while negative out
     */
    'change'?: string;
    /**
     * Balance after change
     */
    'balance'?: string;
    /**
     * Account change type, including:  - in: transferals into cross margin account - out: transferals out from cross margin account - repay: loan repayment - borrow: borrowed loan - interest: interest - new_order: new order locked - order_fill: order fills - referral_fee: fee refund from referrals - order_fee: order fee generated from fills - unknown: unknown type
     */
    'type'?: CrossMarginAccountBook.Type;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'id',
            baseName: 'id',
            type: 'string',
        },
        {
            name: 'time',
            baseName: 'time',
            type: 'number',
        },
        {
            name: 'currency',
            baseName: 'currency',
            type: 'string',
        },
        {
            name: 'change',
            baseName: 'change',
            type: 'string',
        },
        {
            name: 'balance',
            baseName: 'balance',
            type: 'string',
        },
        {
            name: 'type',
            baseName: 'type',
            type: 'CrossMarginAccountBook.Type',
        },
    ];

    static getAttributeTypeMap() {
        return CrossMarginAccountBook.attributeTypeMap;
    }
}

export namespace CrossMarginAccountBook {
    export enum Type {
        In = <any>'in',
        Out = <any>'out',
        Repay = <any>'repay',
        Borrow = <any>'borrow',
        Interest = <any>'interest',
        NewOrder = <any>'new_order',
        OrderFill = <any>'order_fill',
        ReferralFee = <any>'referral_fee',
        OrderFee = <any>'order_fee',
        Unknown = <any>'unknown',
    }
}
