/**
 * Gate API v4
 * Welcome to Gate API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user\'s behalf.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class Currency2 {
    /**
     * Currency symbol
     */
    'currency'?: string;
    /**
     * Currency name
     */
    'name'?: string;
    /**
     * The main chain corresponding to the coin
     */
    'chain'?: string;
    /**
     * Contract Address
     */
    'address'?: string;
    /**
     * Amount scale
     */
    'amountPrecision'?: number;
    /**
     * Price scale
     */
    'precision'?: number;
    /**
     * 币种交易状态 - `1` : 正常交易 - `2` : 暂停交易 - `3` : 下架
     */
    'status'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'currency',
            baseName: 'currency',
            type: 'string',
        },
        {
            name: 'name',
            baseName: 'name',
            type: 'string',
        },
        {
            name: 'chain',
            baseName: 'chain',
            type: 'string',
        },
        {
            name: 'address',
            baseName: 'address',
            type: 'string',
        },
        {
            name: 'amountPrecision',
            baseName: 'amount_precision',
            type: 'number',
        },
        {
            name: 'precision',
            baseName: 'precision',
            type: 'number',
        },
        {
            name: 'status',
            baseName: 'status',
            type: 'number',
        },
    ];

    static getAttributeTypeMap() {
        return Currency2.attributeTypeMap;
    }
}
