/**
 * Gate API v4
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user\'s behalf.
 *
 * Contact: support@mail.gate.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Currency Quota
*/
export class CurrencyQuota {
    /**
    * Currency
    */
    'currency'?: string;
    /**
    * Currency Index Price
    */
    'indexPrice'?: string;
    /**
    * Minimum borrowing/collateral quota for the currency
    */
    'minQuota'?: string;
    /**
    * Remaining borrowing/collateral limit for the currency
    */
    'leftQuota'?: string;
    /**
    * Remaining currency limit converted to USDT
    */
    'leftQuoteUsdt'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "indexPrice",
            "baseName": "index_price",
            "type": "string"
        },
        {
            "name": "minQuota",
            "baseName": "min_quota",
            "type": "string"
        },
        {
            "name": "leftQuota",
            "baseName": "left_quota",
            "type": "string"
        },
        {
            "name": "leftQuoteUsdt",
            "baseName": "left_quote_usdt",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CurrencyQuota.attributeTypeMap;
    }
}

