/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class DualGetOrders {
    /**
     * Order ID
     */
    'id'?: number;
    /**
     * Product ID
     */
    'planId'?: number;
    /**
     * Units
     */
    'copies'?: string;
    /**
     * Investment Quantity
     */
    'investAmount'?: string;
    /**
     * Settlement Quantity
     */
    'settlementAmount'?: string;
    /**
     * Created time
     */
    'createTime'?: number;
    /**
     * Completed Time
     */
    'completeTime'?: number;
    /**
     * Status:  `INIT`-Created `SETTLEMENT_SUCCESS`-Settlement Success `SETTLEMENT_PROCESSING`-Settlement Processing `CANCELED`-Canceled `FAILED`-Failed
     */
    'status'?: string;
    /**
     * Investment Token
     */
    'investCurrency'?: string;
    /**
     * Strike Token
     */
    'exerciseCurrency'?: string;
    /**
     * Strike price
     */
    'exercisePrice'?: string;
    /**
     * Settlement price
     */
    'settlementPrice'?: string;
    /**
     * Settlement currency
     */
    'settlementCurrency'?: string;
    /**
     * Annual Yield
     */
    'apyDisplay'?: string;
    /**
     * Settlement Annual Yield
     */
    'apySettlement'?: string;
    /**
     * Settlement time
     */
    'deliveryTime'?: number;
    /**
     * Custom order information
     */
    'text'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'id',
            baseName: 'id',
            type: 'number',
        },
        {
            name: 'planId',
            baseName: 'plan_id',
            type: 'number',
        },
        {
            name: 'copies',
            baseName: 'copies',
            type: 'string',
        },
        {
            name: 'investAmount',
            baseName: 'invest_amount',
            type: 'string',
        },
        {
            name: 'settlementAmount',
            baseName: 'settlement_amount',
            type: 'string',
        },
        {
            name: 'createTime',
            baseName: 'create_time',
            type: 'number',
        },
        {
            name: 'completeTime',
            baseName: 'complete_time',
            type: 'number',
        },
        {
            name: 'status',
            baseName: 'status',
            type: 'string',
        },
        {
            name: 'investCurrency',
            baseName: 'invest_currency',
            type: 'string',
        },
        {
            name: 'exerciseCurrency',
            baseName: 'exercise_currency',
            type: 'string',
        },
        {
            name: 'exercisePrice',
            baseName: 'exercise_price',
            type: 'string',
        },
        {
            name: 'settlementPrice',
            baseName: 'settlement_price',
            type: 'string',
        },
        {
            name: 'settlementCurrency',
            baseName: 'settlement_currency',
            type: 'string',
        },
        {
            name: 'apyDisplay',
            baseName: 'apy_display',
            type: 'string',
        },
        {
            name: 'apySettlement',
            baseName: 'apy_settlement',
            type: 'string',
        },
        {
            name: 'deliveryTime',
            baseName: 'delivery_time',
            type: 'number',
        },
        {
            name: 'text',
            baseName: 'text',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return DualGetOrders.attributeTypeMap;
    }
}
