/**
 * Gate API v4
 * Welcome to Gate API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user\'s behalf.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class DualGetPlans {
    /**
     * Plan ID
     */
    'id'?: number;
    /**
     * Instrument Name
     */
    'instrumentName'?: string;
    /**
     * Investment Currency
     */
    'investCurrency'?: string;
    /**
     * Strike Currency
     */
    'exerciseCurrency'?: string;
    /**
     * Strike price
     */
    'exercisePrice'?: number;
    /**
     * Settlement time
     */
    'deliveryTime'?: number;
    /**
     * Minimum Copies
     */
    'minCopies'?: number;
    /**
     * Maximum Copies
     */
    'maxCopies'?: number;
    /**
     * Per Unit Value
     */
    'perValue'?: string;
    /**
     * APY
     */
    'apyDisplay'?: string;
    /**
     * start time
     */
    'startTime'?: number;
    /**
     * Finished time
     */
    'endTime'?: number;
    /**
     * Status:   `NOTSTARTED`-not started  `ONGOING`-ongoing  `ENDED`-ended
     */
    'status'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'id',
            baseName: 'id',
            type: 'number',
        },
        {
            name: 'instrumentName',
            baseName: 'instrument_name',
            type: 'string',
        },
        {
            name: 'investCurrency',
            baseName: 'invest_currency',
            type: 'string',
        },
        {
            name: 'exerciseCurrency',
            baseName: 'exercise_currency',
            type: 'string',
        },
        {
            name: 'exercisePrice',
            baseName: 'exercise_price',
            type: 'number',
        },
        {
            name: 'deliveryTime',
            baseName: 'delivery_time',
            type: 'number',
        },
        {
            name: 'minCopies',
            baseName: 'min_copies',
            type: 'number',
        },
        {
            name: 'maxCopies',
            baseName: 'max_copies',
            type: 'number',
        },
        {
            name: 'perValue',
            baseName: 'per_value',
            type: 'string',
        },
        {
            name: 'apyDisplay',
            baseName: 'apy_display',
            type: 'string',
        },
        {
            name: 'startTime',
            baseName: 'start_time',
            type: 'number',
        },
        {
            name: 'endTime',
            baseName: 'end_time',
            type: 'number',
        },
        {
            name: 'status',
            baseName: 'status',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return DualGetPlans.attributeTypeMap;
    }
}
