/**
 * Gate API
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Parameters of flash swap order creation.
 */
export class FlashSwapPreviewRequest {
    /**
     * The name of the asset being sold, as obtained from the \"GET /flash_swap/currency_pairs\" API, which retrieves a list of supported flash swap currency pairs.
     */
    'sellCurrency': string;
    /**
     * Amount to sell. It is required to choose one parameter between `sell_amount` and `buy_amount`
     */
    'sellAmount'?: string;
    /**
     * The name of the asset being purchased, as obtained from the \"GET /flash_swap/currency_pairs\" API, which provides a list of supported flash swap currency pairs.
     */
    'buyCurrency': string;
    /**
     * Amount to buy. It is required to choose one parameter between `sell_amount` and `buy_amount`
     */
    'buyAmount'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'sellCurrency',
            baseName: 'sell_currency',
            type: 'string',
        },
        {
            name: 'sellAmount',
            baseName: 'sell_amount',
            type: 'string',
        },
        {
            name: 'buyCurrency',
            baseName: 'buy_currency',
            type: 'string',
        },
        {
            name: 'buyAmount',
            baseName: 'buy_amount',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return FlashSwapPreviewRequest.attributeTypeMap;
    }
}
