/**
 * Gate API
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class FuturesLiquidate {
    /**
     * Liquidation time
     */
    'time'?: number;
    /**
     * Futures contract
     */
    'contract'?: string;
    /**
     * Position leverage. Not returned in public endpoints.
     */
    'leverage'?: string;
    /**
     * Position size
     */
    'size'?: number;
    /**
     * Position margin. Not returned in public endpoints.
     */
    'margin'?: string;
    /**
     * Average entry price. Not returned in public endpoints.
     */
    'entryPrice'?: string;
    /**
     * Liquidation price. Not returned in public endpoints.
     */
    'liqPrice'?: string;
    /**
     * Mark price. Not returned in public endpoints.
     */
    'markPrice'?: string;
    /**
     * Liquidation order ID. Not returned in public endpoints.
     */
    'orderId'?: number;
    /**
     * Liquidation order price
     */
    'orderPrice'?: string;
    /**
     * Liquidation order average taker price
     */
    'fillPrice'?: string;
    /**
     * Liquidation order maker size
     */
    'left'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'time',
            baseName: 'time',
            type: 'number',
        },
        {
            name: 'contract',
            baseName: 'contract',
            type: 'string',
        },
        {
            name: 'leverage',
            baseName: 'leverage',
            type: 'string',
        },
        {
            name: 'size',
            baseName: 'size',
            type: 'number',
        },
        {
            name: 'margin',
            baseName: 'margin',
            type: 'string',
        },
        {
            name: 'entryPrice',
            baseName: 'entry_price',
            type: 'string',
        },
        {
            name: 'liqPrice',
            baseName: 'liq_price',
            type: 'string',
        },
        {
            name: 'markPrice',
            baseName: 'mark_price',
            type: 'string',
        },
        {
            name: 'orderId',
            baseName: 'order_id',
            type: 'number',
        },
        {
            name: 'orderPrice',
            baseName: 'order_price',
            type: 'string',
        },
        {
            name: 'fillPrice',
            baseName: 'fill_price',
            type: 'string',
        },
        {
            name: 'left',
            baseName: 'left',
            type: 'number',
        },
    ];

    static getAttributeTypeMap() {
        return FuturesLiquidate.attributeTypeMap;
    }
}
