/**
 * Gate API v4
 * APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user\'s behalf.
 *
 * Contact: support@mail.gate.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FuturesInitialOrder } from './futuresInitialOrder';
import { FuturesPriceTrigger } from './futuresPriceTrigger';

/**
 * Futures order details
 */
export class FuturesPriceTriggeredOrder {
    'initial': FuturesInitialOrder;
    'trigger': FuturesPriceTrigger;
    /**
     * Auto order ID
     */
    'id'?: number;
    /**
     * User ID
     */
    'user'?: number;
    /**
     * Creation time
     */
    'createTime'?: number;
    /**
     * Finished time
     */
    'finishTime'?: number;
    /**
     * ID of the newly created order on condition triggered
     */
    'tradeId'?: number;
    /**
     * Order status.
     */
    'status'?: FuturesPriceTriggeredOrder.Status;
    /**
     * How order is finished
     */
    'finishAs'?: FuturesPriceTriggeredOrder.FinishAs;
    /**
     * Extra messages of how order is finished
     */
    'reason'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: { name: string; baseName: string; type: string }[] = [
        {
            name: 'initial',
            baseName: 'initial',
            type: 'FuturesInitialOrder',
        },
        {
            name: 'trigger',
            baseName: 'trigger',
            type: 'FuturesPriceTrigger',
        },
        {
            name: 'id',
            baseName: 'id',
            type: 'number',
        },
        {
            name: 'user',
            baseName: 'user',
            type: 'number',
        },
        {
            name: 'createTime',
            baseName: 'create_time',
            type: 'number',
        },
        {
            name: 'finishTime',
            baseName: 'finish_time',
            type: 'number',
        },
        {
            name: 'tradeId',
            baseName: 'trade_id',
            type: 'number',
        },
        {
            name: 'status',
            baseName: 'status',
            type: 'FuturesPriceTriggeredOrder.Status',
        },
        {
            name: 'finishAs',
            baseName: 'finish_as',
            type: 'FuturesPriceTriggeredOrder.FinishAs',
        },
        {
            name: 'reason',
            baseName: 'reason',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return FuturesPriceTriggeredOrder.attributeTypeMap;
    }
}

export namespace FuturesPriceTriggeredOrder {
    export enum Status {
        Open = <any>'open',
        Finished = <any>'finished',
    }
    export enum FinishAs {
        Cancelled = <any>'cancelled',
        Succeeded = <any>'succeeded',
        Failed = <any>'failed',
        Expired = <any>'expired',
    }
}
