/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The returned result is a map type, where the key represents the market and taker and maker fee rates
 */
export class FuturesFee {
    /**
     * Taker fee
     */
    'takerFee'?: string;
    /**
     * maker fee
     */
    'makerFee'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'takerFee',
            baseName: 'taker_fee',
            type: 'string',
        },
        {
            name: 'makerFee',
            baseName: 'maker_fee',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return FuturesFee.attributeTypeMap;
    }
}
