/**
 * Gate API
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FuturesOrderBookItem } from './futuresOrderBookItem';

export class FuturesOrderBook {
    /**
     * Order Book ID. Increases by 1 on every order book change. Set `with_id=true` to include this field in response
     */
    'id'?: number;
    /**
     * Response data generation timestamp
     */
    'current'?: number;
    /**
     * Order book changed timestamp
     */
    'update'?: number;
    /**
     * Asks order depth
     */
    'asks': Array<FuturesOrderBookItem>;
    /**
     * Bids order depth
     */
    'bids': Array<FuturesOrderBookItem>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'id',
            baseName: 'id',
            type: 'number',
        },
        {
            name: 'current',
            baseName: 'current',
            type: 'number',
        },
        {
            name: 'update',
            baseName: 'update',
            type: 'number',
        },
        {
            name: 'asks',
            baseName: 'asks',
            type: 'Array<FuturesOrderBookItem>',
        },
        {
            name: 'bids',
            baseName: 'bids',
            type: 'Array<FuturesOrderBookItem>',
        },
    ];

    static getAttributeTypeMap() {
        return FuturesOrderBook.attributeTypeMap;
    }
}
