/**
 * Gate API
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class InlineObject {
    /**
     * Full position-by-position model, ISOLATED-by-position, CROSS-full position.
     */
    'mode': string;
    /**
     * Contract Market.
     */
    'contract': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'mode',
            baseName: 'mode',
            type: 'string',
        },
        {
            name: 'contract',
            baseName: 'contract',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return InlineObject.attributeTypeMap;
    }
}
