/**
 * Gate API
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class InsuranceRecord {
    /**
     * Unix timestamp in seconds.
     */
    't'?: number;
    /**
     * Insurance balance.
     */
    'b'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 't',
            baseName: 't',
            type: 'number',
        },
        {
            name: 'b',
            baseName: 'b',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return InsuranceRecord.attributeTypeMap;
    }
}
