/**
 * Gate API
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MarginAccountCurrency } from './marginAccountCurrency';

/**
 * Margin account detail. `base` refers to base currency, while `quotes to quote currency
 */
export class MarginAccount {
    /**
     * Currency pair.
     */
    'currencyPair'?: string;
    /**
     * Account type, risk - risk rate account, mmr - maintenance margin market not activated
     */
    'accountType'?: string;
    /**
     * User current market leverage multiple.
     */
    'leverage'?: string;
    /**
     * Whether account is locked.
     */
    'locked'?: boolean;
    /**
     * Leveraged Account Current Risk Rate (Returned when the Account is a Risk Rate Account)
     */
    'risk'?: string;
    /**
     * Leveraged Account Current Maintenance Margin Rate (returned when the Account is Account)
     */
    'mmr'?: string;
    'base'?: MarginAccountCurrency;
    'quote'?: MarginAccountCurrency;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'currencyPair',
            baseName: 'currency_pair',
            type: 'string',
        },
        {
            name: 'accountType',
            baseName: 'account_type',
            type: 'string',
        },
        {
            name: 'leverage',
            baseName: 'leverage',
            type: 'string',
        },
        {
            name: 'locked',
            baseName: 'locked',
            type: 'boolean',
        },
        {
            name: 'risk',
            baseName: 'risk',
            type: 'string',
        },
        {
            name: 'mmr',
            baseName: 'mmr',
            type: 'string',
        },
        {
            name: 'base',
            baseName: 'base',
            type: 'MarginAccountCurrency',
        },
        {
            name: 'quote',
            baseName: 'quote',
            type: 'MarginAccountCurrency',
        },
    ];

    static getAttributeTypeMap() {
        return MarginAccount.attributeTypeMap;
    }
}
