/**
 * Gate API v4
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user\'s behalf.
 *
 * Contact: support@mail.gate.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class MarginAccountBook {
    /**
     * Balance change record ID
     */
    'id'?: string;
    /**
     * Balance changed timestamp
     */
    'time'?: string;
    /**
     * The timestamp of the change (in milliseconds)
     */
    'timeMs'?: number;
    /**
     * Currency changed
     */
    'currency'?: string;
    /**
     * Account currency pair
     */
    'currencyPair'?: string;
    /**
     * Amount changed. Positive value means transferring in, while negative out
     */
    'change'?: string;
    /**
     * Balance after change
     */
    'balance'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'id',
            baseName: 'id',
            type: 'string',
        },
        {
            name: 'time',
            baseName: 'time',
            type: 'string',
        },
        {
            name: 'timeMs',
            baseName: 'time_ms',
            type: 'number',
        },
        {
            name: 'currency',
            baseName: 'currency',
            type: 'string',
        },
        {
            name: 'currencyPair',
            baseName: 'currency_pair',
            type: 'string',
        },
        {
            name: 'change',
            baseName: 'change',
            type: 'string',
        },
        {
            name: 'balance',
            baseName: 'balance',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return MarginAccountBook.attributeTypeMap;
    }
}
