/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class MarginTiers {
    /**
     * Tier
     */
    'tier'?: string;
    /**
     * Discount
     */
    'marginRate'?: string;
    /**
     * Lower limit
     */
    'lowerLimit'?: string;
    /**
     * Upper limit, \"\" indicates greater than (the last tier)
     */
    'upperLimit'?: string;
    /**
     * Position leverage
     */
    'leverage'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'tier',
            baseName: 'tier',
            type: 'string',
        },
        {
            name: 'marginRate',
            baseName: 'margin_rate',
            type: 'string',
        },
        {
            name: 'lowerLimit',
            baseName: 'lower_limit',
            type: 'string',
        },
        {
            name: 'upperLimit',
            baseName: 'upper_limit',
            type: 'string',
        },
        {
            name: 'leverage',
            baseName: 'leverage',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return MarginTiers.attributeTypeMap;
    }
}
