/**
 * Gate API v4
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user\'s behalf.
 *
 * Contact: support@mail.gate.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 期权仓位
 */
export class MockOptionsPosition {
    /**
     * 期权名称，目前只支持BTC、ETH的USDT期权
     */
    'optionsName': string;
    /**
     * 仓位大小，单位是张数
     */
    'size': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'optionsName',
            baseName: 'options_name',
            type: 'string',
        },
        {
            name: 'size',
            baseName: 'size',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return MockOptionsPosition.attributeTypeMap;
    }
}
