/**
 * Gate API v4
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user\'s behalf.
 *
 * Contact: support@mail.gate.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProfitLossRange } from './profitLossRange';

/**
 * 保证金结果
 */
export class MockMarginResult {
    /**
     * 仓位组合类型 `original_position` - 原始仓位 `long_delta_original_position` - 正向delta+原始仓位 `short_delta_original_position` - 负向delta+原始仓位
     */
    'type'?: string;
    /**
     * mr1的33个压力场景测试结果
     */
    'profitLossRanges'?: Array<ProfitLossRange>;
    /**
     * 最大损失
     */
    'maxLoss'?: ProfitLossRange;
    /**
     * 压力测试
     */
    'mr1'?: string;
    /**
     * 基差跨期风险
     */
    'mr2'?: string;
    /**
     * 波动率跨期风险
     */
    'mr3'?: string;
    /**
     * 期权空头风险
     */
    'mr4'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'type',
            baseName: 'type',
            type: 'string',
        },
        {
            name: 'profitLossRanges',
            baseName: 'profit_loss_ranges',
            type: 'Array<ProfitLossRange>',
        },
        {
            name: 'maxLoss',
            baseName: 'max_loss',
            type: 'ProfitLossRange',
        },
        {
            name: 'mr1',
            baseName: 'mr1',
            type: 'string',
        },
        {
            name: 'mr2',
            baseName: 'mr2',
            type: 'string',
        },
        {
            name: 'mr3',
            baseName: 'mr3',
            type: 'string',
        },
        {
            name: 'mr4',
            baseName: 'mr4',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return MockMarginResult.attributeTypeMap;
    }
}
