/**
 * Gate API v4
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user\'s behalf.
 *
 * Contact: support@mail.gate.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RepayRecordCurrency } from './repayRecordCurrency';
import { RepayRecordLeftInterest } from './repayRecordLeftInterest';
import { RepayRecordRepaidCurrency } from './repayRecordRepaidCurrency';
import { RepayRecordTotalInterest } from './repayRecordTotalInterest';

/**
* Mult Repay Record
*/
export class MultiRepayRecord {
    /**
    * Order ID
    */
    'orderId'?: number;
    /**
    * Repayment record ID
    */
    'recordId'?: number;
    /**
    * The initial collateralization rate
    */
    'initLtv'?: string;
    /**
    * Ltv before the operation
    */
    'beforeLtv'?: string;
    /**
    * Ltv after the operation
    */
    'afterLtv'?: string;
    /**
    * Borrowing time, timestamp in seconds.
    */
    'borrowTime'?: number;
    /**
    * Repayment time, timestamp in seconds.
    */
    'repayTime'?: number;
    /**
    * List of borrowing information
    */
    'borrowCurrencies'?: Array<RepayRecordCurrency>;
    /**
    * List of collateral information
    */
    'collateralCurrencies'?: Array<RepayRecordCurrency>;
    /**
    * Repay Currency List
    */
    'repaidCurrencies'?: Array<RepayRecordRepaidCurrency>;
    /**
    * Total Interest List
    */
    'totalInterestList'?: Array<RepayRecordTotalInterest>;
    /**
    * List of left repay interest
    */
    'leftRepayInterestList'?: Array<RepayRecordLeftInterest>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "number"
        },
        {
            "name": "recordId",
            "baseName": "record_id",
            "type": "number"
        },
        {
            "name": "initLtv",
            "baseName": "init_ltv",
            "type": "string"
        },
        {
            "name": "beforeLtv",
            "baseName": "before_ltv",
            "type": "string"
        },
        {
            "name": "afterLtv",
            "baseName": "after_ltv",
            "type": "string"
        },
        {
            "name": "borrowTime",
            "baseName": "borrow_time",
            "type": "number"
        },
        {
            "name": "repayTime",
            "baseName": "repay_time",
            "type": "number"
        },
        {
            "name": "borrowCurrencies",
            "baseName": "borrow_currencies",
            "type": "Array<RepayRecordCurrency>"
        },
        {
            "name": "collateralCurrencies",
            "baseName": "collateral_currencies",
            "type": "Array<RepayRecordCurrency>"
        },
        {
            "name": "repaidCurrencies",
            "baseName": "repaid_currencies",
            "type": "Array<RepayRecordRepaidCurrency>"
        },
        {
            "name": "totalInterestList",
            "baseName": "total_interest_list",
            "type": "Array<RepayRecordTotalInterest>"
        },
        {
            "name": "leftRepayInterestList",
            "baseName": "left_repay_interest_list",
            "type": "Array<RepayRecordLeftInterest>"
        }    ];

    static getAttributeTypeMap() {
        return MultiRepayRecord.attributeTypeMap;
    }
}

