/**
 * Gate API
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class OptionsPositionClose {
    /**
     * Position close time.
     */
    'time'?: number;
    /**
     * Options contract name.
     */
    'contract'?: string;
    /**
     * Position side, long or short.
     */
    'side'?: OptionsPositionClose.Side;
    /**
     * PNL.
     */
    'pnl'?: string;
    /**
     * Text of close order.
     */
    'text'?: string;
    /**
     * settlement size.
     */
    'settleSize'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'time',
            baseName: 'time',
            type: 'number',
        },
        {
            name: 'contract',
            baseName: 'contract',
            type: 'string',
        },
        {
            name: 'side',
            baseName: 'side',
            type: 'OptionsPositionClose.Side',
        },
        {
            name: 'pnl',
            baseName: 'pnl',
            type: 'string',
        },
        {
            name: 'text',
            baseName: 'text',
            type: 'string',
        },
        {
            name: 'settleSize',
            baseName: 'settle_size',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return OptionsPositionClose.attributeTypeMap;
    }
}

export namespace OptionsPositionClose {
    export enum Side {
        Long = <any>'long',
        Short = <any>'short',
    }
}
