/**
 * Gate API
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Profit and loss range.
 */
export class ProfitLossRange {
    /**
     * Percentage change in price.
     */
    'pricePercentage'?: string;
    /**
     * Percentage change in implied volatility.
     */
    'impliedVolatilityPercentage'?: string;
    /**
     * PNL.
     */
    'profitLoss'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'pricePercentage',
            baseName: 'price_percentage',
            type: 'string',
        },
        {
            name: 'impliedVolatilityPercentage',
            baseName: 'implied_volatility_percentage',
            type: 'string',
        },
        {
            name: 'profitLoss',
            baseName: 'profit_loss',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return ProfitLossRange.attributeTypeMap;
    }
}
