/**
 * Gate API v4
 * Welcome to Gate API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user\'s behalf.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Quotation Response
 */
export class QuoteResponse {
    /**
     * The quotation ID (quote_id) is used for placing orders and is valid for 1 minute
     */
    'quoteId'?: string;
    /**
     * 最小下单量
     */
    'minAmount'?: string;
    /**
     * 最大下单量
     */
    'maxAmount'?: string;
    /**
     * Coin Price (USDT-based)
     */
    'price'?: string;
    /**
     * Slippage
     */
    'slippage'?: string;
    /**
     * Estimated Network Fee (USDT-based)
     */
    'estimateGasFeeAmountUsdt'?: string;
    /**
     * Slippage value of 10 represents a 10% tolerance
     */
    'orderFee'?: string;
    /**
     * 最小获得数量
     */
    'targetTokenMinAmount'?: string;
    /**
     * 最大获得数量
     */
    'targetTokenMaxAmount'?: string;
    /**
     * Failure Type - `0` : Success - `1` : Exceeds maximum value - `2` : Below minimum value
     */
    'errorType'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'quoteId',
            baseName: 'quote_id',
            type: 'string',
        },
        {
            name: 'minAmount',
            baseName: 'min_amount',
            type: 'string',
        },
        {
            name: 'maxAmount',
            baseName: 'max_amount',
            type: 'string',
        },
        {
            name: 'price',
            baseName: 'price',
            type: 'string',
        },
        {
            name: 'slippage',
            baseName: 'slippage',
            type: 'string',
        },
        {
            name: 'estimateGasFeeAmountUsdt',
            baseName: 'estimate_gas_fee_amount_usdt',
            type: 'string',
        },
        {
            name: 'orderFee',
            baseName: 'order_fee',
            type: 'string',
        },
        {
            name: 'targetTokenMinAmount',
            baseName: 'target_token_min_amount',
            type: 'string',
        },
        {
            name: 'targetTokenMaxAmount',
            baseName: 'target_token_max_amount',
            type: 'string',
        },
        {
            name: 'errorType',
            baseName: 'error_type',
            type: 'number',
        },
    ];

    static getAttributeTypeMap() {
        return QuoteResponse.attributeTypeMap;
    }
}
