/**
 * Gate API v4
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user\'s behalf.
 *
 * Contact: support@mail.gate.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 还款记录
 */
export class RepayRecord {
    /**
     * 订单id
     */
    'orderId'?: number;
    /**
     * 还款记录 id
     */
    'recordId'?: number;
    /**
     * Repayment amount
     */
    'repaidAmount'?: string;
    /**
     * 借款币种
     */
    'borrowCurrency'?: string;
    /**
     * 质押币种
     */
    'collateralCurrency'?: string;
    /**
     * 初始质押率
     */
    'initLtv'?: string;
    /**
     * 借款时间，时间戳
     */
    'borrowTime'?: number;
    /**
     * 还款时间，时间戳
     */
    'repayTime'?: number;
    /**
     * 总计息
     */
    'totalInterest'?: string;
    /**
     * 还款前待还本金
     */
    'beforeLeftPrincipal'?: string;
    /**
     * 还款后待还本金
     */
    'afterLeftPrincipal'?: string;
    /**
     * 还款前质押物数量
     */
    'beforeLeftCollateral'?: string;
    /**
     * 还款后质押物数量
     */
    'afterLeftCollateral'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'orderId',
            baseName: 'order_id',
            type: 'number',
        },
        {
            name: 'recordId',
            baseName: 'record_id',
            type: 'number',
        },
        {
            name: 'repaidAmount',
            baseName: 'repaid_amount',
            type: 'string',
        },
        {
            name: 'borrowCurrency',
            baseName: 'borrow_currency',
            type: 'string',
        },
        {
            name: 'collateralCurrency',
            baseName: 'collateral_currency',
            type: 'string',
        },
        {
            name: 'initLtv',
            baseName: 'init_ltv',
            type: 'string',
        },
        {
            name: 'borrowTime',
            baseName: 'borrow_time',
            type: 'number',
        },
        {
            name: 'repayTime',
            baseName: 'repay_time',
            type: 'number',
        },
        {
            name: 'totalInterest',
            baseName: 'total_interest',
            type: 'string',
        },
        {
            name: 'beforeLeftPrincipal',
            baseName: 'before_left_principal',
            type: 'string',
        },
        {
            name: 'afterLeftPrincipal',
            baseName: 'after_left_principal',
            type: 'string',
        },
        {
            name: 'beforeLeftCollateral',
            baseName: 'before_left_collateral',
            type: 'string',
        },
        {
            name: 'afterLeftCollateral',
            baseName: 'after_left_collateral',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return RepayRecord.attributeTypeMap;
    }
}
