/**
 * Gate API v4
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user\'s behalf.
 *
 * Contact: support@mail.gate.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class SavedAddress {
    /**
     * Currency
     */
    'currency'?: string;
    /**
     * Chain name
     */
    'chain'?: string;
    /**
     * Address
     */
    'address'?: string;
    /**
     * Name
     */
    'name'?: string;
    /**
     * Tag
     */
    'tag'?: string;
    /**
     * Whether to pass the verification 0-unverified, 1-verified
     */
    'verified'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'currency',
            baseName: 'currency',
            type: 'string',
        },
        {
            name: 'chain',
            baseName: 'chain',
            type: 'string',
        },
        {
            name: 'address',
            baseName: 'address',
            type: 'string',
        },
        {
            name: 'name',
            baseName: 'name',
            type: 'string',
        },
        {
            name: 'tag',
            baseName: 'tag',
            type: 'string',
        },
        {
            name: 'verified',
            baseName: 'verified',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return SavedAddress.attributeTypeMap;
    }
}
