/**
 * Gate API
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class SpotPriceTrigger {
    /**
     * Trigger price
     */
    'price': string;
    /**
     * Price trigger condition  - `>=`: triggered when market price larger than or equal to `price` field - `<=`: triggered when market price less than or equal to `price` field
     */
    'rule': SpotPriceTrigger.Rule;
    /**
     * How long (in seconds) to wait for the condition to be triggered before cancelling the order.
     */
    'expiration': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'price',
            baseName: 'price',
            type: 'string',
        },
        {
            name: 'rule',
            baseName: 'rule',
            type: 'SpotPriceTrigger.Rule',
        },
        {
            name: 'expiration',
            baseName: 'expiration',
            type: 'number',
        },
    ];

    static getAttributeTypeMap() {
        return SpotPriceTrigger.attributeTypeMap;
    }
}

export namespace SpotPriceTrigger {
    export enum Rule {
        GreaterThanOrEqualTo = <any>'>=',
        LessThanOrEqualTo = <any>'<=',
    }
}
