/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Structured Investment
 */
export class StructuredGetProjectList {
    /**
     * Product ID
     */
    'id'?: number;
    /**
     * Product Type:   `SharkFin2.0`-Shark Fin 2.0  `BullishSharkFin`-Bullish Shark Fin  `BearishSharkFin`-Bearish Shark Fin `DoubleNoTouch`-Double No-Touch `RangeAccrual`-Range Accrual `SnowBall`-Snow Ball
     */
    'type'?: string;
    /**
     * Product Name
     */
    'nameEn'?: string;
    /**
     * Investment Token
     */
    'investmentCoin'?: string;
    /**
     * Investment Period
     */
    'investmentPeriod'?: string;
    /**
     * Minimum Annual Rate
     */
    'minAnnualRate'?: string;
    /**
     * Intermediate Annual Rate
     */
    'midAnnualRate'?: string;
    /**
     * Maximum Annual Rate
     */
    'maxAnnualRate'?: string;
    /**
     * Underlying Market
     */
    'watchMarket'?: string;
    /**
     * Start Time
     */
    'startTime'?: number;
    /**
     * End time
     */
    'endTime'?: number;
    /**
     * Status:   `in_process`-in progress  `will_begin`-will begin  `wait_settlement`-waiting for settlement  `done`-done
     */
    'status'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'id',
            baseName: 'id',
            type: 'number',
        },
        {
            name: 'type',
            baseName: 'type',
            type: 'string',
        },
        {
            name: 'nameEn',
            baseName: 'name_en',
            type: 'string',
        },
        {
            name: 'investmentCoin',
            baseName: 'investment_coin',
            type: 'string',
        },
        {
            name: 'investmentPeriod',
            baseName: 'investment_period',
            type: 'string',
        },
        {
            name: 'minAnnualRate',
            baseName: 'min_annual_rate',
            type: 'string',
        },
        {
            name: 'midAnnualRate',
            baseName: 'mid_annual_rate',
            type: 'string',
        },
        {
            name: 'maxAnnualRate',
            baseName: 'max_annual_rate',
            type: 'string',
        },
        {
            name: 'watchMarket',
            baseName: 'watch_market',
            type: 'string',
        },
        {
            name: 'startTime',
            baseName: 'start_time',
            type: 'number',
        },
        {
            name: 'endTime',
            baseName: 'end_time',
            type: 'number',
        },
        {
            name: 'status',
            baseName: 'status',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return StructuredGetProjectList.attributeTypeMap;
    }
}
