/**
 * Gate API v4
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user\'s behalf.
 *
 * Contact: support@mail.gate.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Dual Investment order
 */
export class StructuredGetProjectListRequest {
    /**
     *  Product Type, default to empty for querying all.  `SharkFin2.0`-Shark Fin 2.0  `BullishSharkFin`-Bullish Shark Fin  `BearishSharkFin`-Bearish Shark Fin  `DoubleNoTouch`-Double No-Touch  `RangeAccrual`-RangeAccrual  `SnowBall`-Snow Ball
     */
    'type'?: string;
    /**
     *  Status: default to empty for querying all.   `in_process`-in progress  `will_begin`-will begin  `wait_settlement`-waiting for settlement  `done`-done
     */
    'status'?: string;
    /**
     * Page number
     */
    'page'?: number;
    /**
     * Number of items returned in the list. Default is 100.
     */
    'limit'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'type',
            baseName: 'type',
            type: 'string',
        },
        {
            name: 'status',
            baseName: 'status',
            type: 'string',
        },
        {
            name: 'page',
            baseName: 'page',
            type: 'number',
        },
        {
            name: 'limit',
            baseName: 'limit',
            type: 'number',
        },
    ];

    static getAttributeTypeMap() {
        return StructuredGetProjectListRequest.attributeTypeMap;
    }
}
