/**
 * Gate API v4
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user\'s behalf.
 *
 * Contact: support@mail.gate.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FuturesAccount } from './futuresAccount';

export class SubAccountFuturesBalance {
    /**
     * User ID
     */
    'uid'?: string;
    /**
     * Futures account balances
     */
    'available'?: { [key: string]: FuturesAccount };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'uid',
            baseName: 'uid',
            type: 'string',
        },
        {
            name: 'available',
            baseName: 'available',
            type: '{ [key: string]: FuturesAccount; }',
        },
    ];

    static getAttributeTypeMap() {
        return SubAccountFuturesBalance.attributeTypeMap;
    }
}
