/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class SubAccount {
    /**
     * Remark
     */
    'remark'?: string;
    /**
     * 子账户登陆名：仅支持字母、数字、下划线，不可包含其他非法字符。
     */
    'loginName': string;
    /**
     * The sub-account\'s password. (Default: the same as main account\'s password)
     */
    'password'?: string;
    /**
     * The sub-account\'s email address. (Default: the same as main account\'s email address)
     */
    'email'?: string;
    /**
     * Sub-account status: 1-normal, 2-locked
     */
    'state'?: number;
    /**
     * Sub-account type: 1-Regular sub-account, 3-Cross margin sub-account
     */
    'type'?: number;
    /**
     * Sub-account user ID
     */
    'userId'?: number;
    /**
     * Created time
     */
    'createTime'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'remark',
            baseName: 'remark',
            type: 'string',
        },
        {
            name: 'loginName',
            baseName: 'login_name',
            type: 'string',
        },
        {
            name: 'password',
            baseName: 'password',
            type: 'string',
        },
        {
            name: 'email',
            baseName: 'email',
            type: 'string',
        },
        {
            name: 'state',
            baseName: 'state',
            type: 'number',
        },
        {
            name: 'type',
            baseName: 'type',
            type: 'number',
        },
        {
            name: 'userId',
            baseName: 'user_id',
            type: 'number',
        },
        {
            name: 'createTime',
            baseName: 'create_time',
            type: 'number',
        },
    ];

    static getAttributeTypeMap() {
        return SubAccount.attributeTypeMap;
    }
}
