/**
 * Gate API v4
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user\'s behalf.
 *
 * Contact: support@mail.gate.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Currency detail
 */
export class UniCurrency {
    /**
     * Currency name
     */
    'currency'?: string;
    /**
     * Minimum lend amount
     */
    'minLendAmount'?: string;
    /**
     * Maximum lend amount
     */
    'maxLendAmount'?: string;
    /**
     * Maximum rate (Hourly)
     */
    'maxRate'?: string;
    /**
     * Minimum rate (Hourly)
     */
    'minRate'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'currency',
            baseName: 'currency',
            type: 'string',
        },
        {
            name: 'minLendAmount',
            baseName: 'min_lend_amount',
            type: 'string',
        },
        {
            name: 'maxLendAmount',
            baseName: 'max_lend_amount',
            type: 'string',
        },
        {
            name: 'maxRate',
            baseName: 'max_rate',
            type: 'string',
        },
        {
            name: 'minRate',
            baseName: 'min_rate',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return UniCurrency.attributeTypeMap;
    }
}
