/**
 * Gate API v4
 * Welcome to Gate API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user\'s behalf.
 *
 * Contact: support@mail.gate.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Currency pair of the loan
 */
export class UniCurrencyPair {
    /**
     * Currency pair
     */
    'currencyPair'?: string;
    /**
     * Minimum borrow amount of base currency
     */
    'baseMinBorrowAmount'?: string;
    /**
     * Minimum borrow amount of quote currency
     */
    'quoteMinBorrowAmount'?: string;
    /**
     * Position leverage
     */
    'leverage'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'currencyPair',
            baseName: 'currency_pair',
            type: 'string',
        },
        {
            name: 'baseMinBorrowAmount',
            baseName: 'base_min_borrow_amount',
            type: 'string',
        },
        {
            name: 'quoteMinBorrowAmount',
            baseName: 'quote_min_borrow_amount',
            type: 'string',
        },
        {
            name: 'leverage',
            baseName: 'leverage',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return UniCurrencyPair.attributeTypeMap;
    }
}
