/**
 * Gate API v4
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user\'s behalf.
 *
 * Contact: support@mail.gate.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class UnifiedSettings {
    /**
     * USDT contract switch. In cross-currency margin mode, it can only be turned on and not off
     */
    'usdtFutures'?: boolean;
    /**
     * Spot hedging switch.
     */
    'spotHedge'?: boolean;
    /**
     * switch, when the mode is cross-currency margin mode, whether to use Uniloan financial funds as margin
     */
    'useFunding'?: boolean;
    /**
     * Option switch. In cross-currency margin mode, it can only be turned on and not off
     */
    'options'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'usdtFutures',
            baseName: 'usdt_futures',
            type: 'boolean',
        },
        {
            name: 'spotHedge',
            baseName: 'spot_hedge',
            type: 'boolean',
        },
        {
            name: 'useFunding',
            baseName: 'use_funding',
            type: 'boolean',
        },
        {
            name: 'options',
            baseName: 'options',
            type: 'boolean',
        },
    ];

    static getAttributeTypeMap() {
        return UnifiedSettings.attributeTypeMap;
    }
}
