/**
 * Gate API
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Loan records
 */
export class UnifiedLoanRecord {
    /**
     * ID
     */
    'id'?: number;
    /**
     * type: borrow - borrow, repay - repay
     */
    'type'?: string;
    /**
     * Repayment type, none - No repayment type, manual_repay - Manual repayment, auto_repay - Automatic repayment, cancel_auto_repay - Automatic repayment after withdrawal, different_currencies_repayment - Different currency repayment
     */
    'repaymentType'?: string;
    /**
     * Loan type, returned when querying loan records. manual_borrow - Manual repayment , auto_borrow - Automatic repayment
     */
    'borrowType'?: string;
    /**
     * Currency pair
     */
    'currencyPair'?: string;
    /**
     * Currency
     */
    'currency'?: string;
    /**
     * The amount of lending or repaying
     */
    'amount'?: string;
    /**
     * Created time
     */
    'createTime'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'id',
            baseName: 'id',
            type: 'number',
        },
        {
            name: 'type',
            baseName: 'type',
            type: 'string',
        },
        {
            name: 'repaymentType',
            baseName: 'repayment_type',
            type: 'string',
        },
        {
            name: 'borrowType',
            baseName: 'borrow_type',
            type: 'string',
        },
        {
            name: 'currencyPair',
            baseName: 'currency_pair',
            type: 'string',
        },
        {
            name: 'currency',
            baseName: 'currency',
            type: 'string',
        },
        {
            name: 'amount',
            baseName: 'amount',
            type: 'string',
        },
        {
            name: 'createTime',
            baseName: 'create_time',
            type: 'number',
        },
    ];

    static getAttributeTypeMap() {
        return UnifiedLoanRecord.attributeTypeMap;
    }
}
