/**
 * Gate API v4
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user\'s behalf.
 *
 * Contact: support@mail.gate.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UnifiedHistoryLoanRateRates } from './unifiedHistoryLoanRateRates';

export class UnifiedHistoryLoanRate {
    /**
     * Currency name
     */
    'currency'?: string;
    /**
     * 需要获取的上浮费率的vip等级
     */
    'tier'?: string;
    /**
     * vip等级对应的上浮费率
     */
    'tierUpRate'?: string;
    /**
     * 历史利率信息，每个整点小时一个数据，数组大小根据接口请求参数提供的page和limit参数确定，按照时间从近到远排序
     */
    'rates'?: Array<UnifiedHistoryLoanRateRates>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'currency',
            baseName: 'currency',
            type: 'string',
        },
        {
            name: 'tier',
            baseName: 'tier',
            type: 'string',
        },
        {
            name: 'tierUpRate',
            baseName: 'tier_up_rate',
            type: 'string',
        },
        {
            name: 'rates',
            baseName: 'rates',
            type: 'Array<UnifiedHistoryLoanRateRates>',
        },
    ];

    static getAttributeTypeMap() {
        return UnifiedHistoryLoanRate.attributeTypeMap;
    }
}
