/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Borrow or repay
 */
export class UnifiedLoan {
    /**
     * Currency
     */
    'currency': string;
    /**
     * Type: `borrow` - borrow, `repay` - repay
     */
    'type': UnifiedLoan.Type;
    /**
     * Borrow or repayment amount
     */
    'amount': string;
    /**
     * Full repayment, only used for repayment operations. When set to `true`, overrides `amount` and directly repays the full amount
     */
    'repaidAll'?: boolean;
    /**
     * User defined custom ID
     */
    'text'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'currency',
            baseName: 'currency',
            type: 'string',
        },
        {
            name: 'type',
            baseName: 'type',
            type: 'UnifiedLoan.Type',
        },
        {
            name: 'amount',
            baseName: 'amount',
            type: 'string',
        },
        {
            name: 'repaidAll',
            baseName: 'repaid_all',
            type: 'boolean',
        },
        {
            name: 'text',
            baseName: 'text',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return UnifiedLoan.attributeTypeMap;
    }
}

export namespace UnifiedLoan {
    export enum Type {
        Borrow = <any>'borrow',
        Repay = <any>'repay',
    }
}
