/**
 * Gate API
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UnifiedSettings } from './unifiedSettings';

export class UnifiedModeSet {
    /**
     * Unified account mode:  - `classic`: Classic account mode - `multi_currency`: Multi-currency margin mode - `portfolio`: Portfolio margin mode - `single_currency`: Single Currency Margin Model
     */
    'mode': string;
    'settings'?: UnifiedSettings;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'mode',
            baseName: 'mode',
            type: 'string',
        },
        {
            name: 'settings',
            baseName: 'settings',
            type: 'UnifiedSettings',
        },
    ];

    static getAttributeTypeMap() {
        return UnifiedModeSet.attributeTypeMap;
    }
}
