/**
 * Gate API v4
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user\'s behalf.
 *
 * Contact: support@mail.gate.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Interest record
*/
export class UniLoanInterestRecord {
    /**
    * Currency name
    */
    'currency'?: string;
    /**
    * Currency pair
    */
    'currencyPair'?: string;
    /**
    * Actual rate
    */
    'actualRate'?: string;
    /**
    * Interest
    */
    'interest'?: string;
    /**
    * Status: 0 - fail, 1 - success
    */
    'status'?: number;
    /**
    * Type, platform - platform，margin - margin
    */
    'type'?: string;
    /**
    * Created time
    */
    'createTime'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "currencyPair",
            "baseName": "currency_pair",
            "type": "string"
        },
        {
            "name": "actualRate",
            "baseName": "actual_rate",
            "type": "string"
        },
        {
            "name": "interest",
            "baseName": "interest",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "number"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "createTime",
            "baseName": "create_time",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return UniLoanInterestRecord.attributeTypeMap;
    }
}

