/**
 * Gate API v4
 * Welcome to Gate API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user\'s behalf.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Loan records
 */
export class UniLoanRecord {
    /**
     * type: borrow - borrow, repay - repay
     */
    'type'?: string;
    /**
     * Currency pair
     */
    'currencyPair'?: string;
    /**
     * Currency
     */
    'currency'?: string;
    /**
     * The amount of lending or repaying
     */
    'amount'?: string;
    /**
     * Created time
     */
    'createTime'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'type',
            baseName: 'type',
            type: 'string',
        },
        {
            name: 'currencyPair',
            baseName: 'currency_pair',
            type: 'string',
        },
        {
            name: 'currency',
            baseName: 'currency',
            type: 'string',
        },
        {
            name: 'amount',
            baseName: 'amount',
            type: 'string',
        },
        {
            name: 'createTime',
            baseName: 'create_time',
            type: 'number',
        },
    ];

    static getAttributeTypeMap() {
        return UniLoanRecord.attributeTypeMap;
    }
}
