/**
 * Gate API v4
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user\'s behalf.
 *
 * Contact: support@mail.gate.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class UserSub {
    /**
     * User ID
     */
    'uid'?: number;
    /**
     * The system to which the user belongs (partner referral). If empty, it means not belonging to any system.
     */
    'belong'?: string;
    /**
     * Type (0-not in the system 1-direct subordinate agent 2-indirect subordinate agent 3-direct direct customer 4-indirect direct customer 5-ordinary user)
     */
    'type'?: number;
    /**
     * Inviter user ID
     */
    'refUid'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'uid',
            baseName: 'uid',
            type: 'number',
        },
        {
            name: 'belong',
            baseName: 'belong',
            type: 'string',
        },
        {
            name: 'type',
            baseName: 'type',
            type: 'number',
        },
        {
            name: 'refUid',
            baseName: 'ref_uid',
            type: 'number',
        },
    ];

    static getAttributeTypeMap() {
        return UserSub.attributeTypeMap;
    }
}
