/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class UserSub {
    /**
     * User ID
     */
    'uid'?: number;
    /**
     * User\'s system affiliation (partner/referral). Empty means not belonging to any system
     */
    'belong'?: string;
    /**
     * Type (0-Not in system 1-Direct subordinate agent 2-Indirect subordinate agent 3-Direct direct customer 4-Indirect direct customer 5-Regular user)
     */
    'type'?: number;
    /**
     * Inviter user ID
     */
    'refUid'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'uid',
            baseName: 'uid',
            type: 'number',
        },
        {
            name: 'belong',
            baseName: 'belong',
            type: 'string',
        },
        {
            name: 'type',
            baseName: 'type',
            type: 'number',
        },
        {
            name: 'refUid',
            baseName: 'ref_uid',
            type: 'number',
        },
    ];

    static getAttributeTypeMap() {
        return UserSub.attributeTypeMap;
    }
}
